### ISSUE TITLE
DNS Management

### ISSUE THREAD

**Issue by sunguroku** [porter-dev/porter#342]
# Location

- [x] Browser
- [ ] CLI
- [x] API

# Requirements

## Generate Default URL's 
When a user deploys an application with **Expose to External traffic** option toggled, we assign a default URL of form: \*.app.getporter.dev.

### Implementation steps
- [ ] Point a wildcard domain to prod load balancer and secure it with `cert-manager`.
- [ ] Create Ingress that uses nginx ingress controller along with a Service of type `ExternalName` on every application deploy. (https://kubernetes.io/docs/concepts/services-networking/service/#externalname)

If the above implementation does not work, use Kong API Gateway as reverse proxy on the production cluster. Considered Kong, Envoy, and Traefik - Traefik and Envoy don't have a robust API to add services on the fly. Kong has something called Admin API that we can use to add `Services` and `Routes`. [See here for details.](https://docs.konghq.com/getting-started-guide/2.1.x/overview/)

## Setting up Custom Domains

If the user wants to set up a custom domain instead of use the default URL, there are two ways to set it up:

1) set up a CNAME/ANAME/ALIAS record that points to the default domain assigned to the specific ingress (\*.app.getporter.dev)

2) set up a CNAME/ANAME/ALIAS/A record that points to the load balancer (static IP or DNS name for EKS) 

1 is the default recommended way, 2 is optional for advanced users who wants to set it up themselves for some reason.

### Implementation Steps
- [ ] A "custom domains" tab in the `form.yaml` of the docker template 
	- [ ] check if not securing the ingress on the user's cluster with `cert-manager` still works if Porter secures the generated URL by default.
